name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Или другой основной веткой, где происходят изменения

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install, build, test
        run: |
          npm install

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Выберите нужную версию Node.js

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: deploy site
        uses: actions/deploy-pages@v4
